import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Link from 'next/link'
import Footer from '@/components/Footer'
import Sidebar from '@/components/Sidebar';

const dashboard = () => {
    return (
        <>
            <Head>
                <title>LegitCar | Maintainance</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="flex justify-between">
                <Sidebar />
                <div className="flex-1 min-h-screen bg-grayBg">
                    <Navbar page={"Dashboard"} />
                    <div className="p-5 max-w-7xl mx-auto">
                        <h1>Dashboard</h1>
                    </div>
                </div>
            </div>
            <Footer />
        </>
    )
}

export default dashboard