import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Link from 'next/link'

const kudos = () => {
    return (
        <>
            <Head>
                <title>LegitCar | Services</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="min-h-screen bg-grayBg">
                <Navbar page={"Maintainance"} />
                <div className="px-5">
                    <div className="flex items-center justify-end mt-4 mb-8">
                        <Link href="/maintainance" className='cursor-pointer'>
                            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <rect width="24" height="24" rx="12" fill="#475467" />
                                <g clip-path="url(#clip0_3616_84485)">
                                    <path d="M8.41369 15.9999C8.30841 15.9999 8.20304 15.96 8.12298 15.8793C7.96226 15.7186 7.96226 15.4579 8.12298 15.2972L15.2991 8.1211C15.4599 7.96028 15.7204 7.96028 15.8812 8.1211C16.0419 8.28182 16.0419 8.54239 15.8812 8.70311L8.70499 15.8793C8.62433 15.96 8.51906 15.9999 8.41369 15.9999Z" fill="white" />
                                    <path d="M15.5904 16C15.4851 16 15.3797 15.96 15.2997 15.8793L8.12298 8.70265C7.96226 8.54183 7.96226 8.28126 8.12298 8.12054C8.2837 7.95982 8.54427 7.95982 8.70499 8.12054L15.8812 15.2972C16.0419 15.4579 16.0419 15.7186 15.8812 15.8793C15.8005 15.96 15.6952 16 15.5904 16Z" fill="white" />
                                </g>
                                <defs>
                                    <clipPath id="clip0_3616_84485">
                                        <rect width="8" height="8" fill="white" transform="translate(8 8)" />
                                    </clipPath>
                                </defs>
                            </svg>
                        </Link>
                    </div>

                    <div className="flex items-center justify-center mb-8">
                        <svg width="80" height="80" viewBox="0 0 80 80" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M30 70.8335C28.6193 70.8335 27.5 69.7142 27.5 68.3335V61.6668C27.5 60.2861 28.6193 59.1668 30 59.1668C31.3807 59.1668 32.5 60.2861 32.5 61.6668V68.3335C32.5 69.7142 31.3807 70.8335 30 70.8335Z" fill="#FF5071" fill-opacity="0.3" />
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M50 69.167C48.6193 69.167 47.5 68.0477 47.5 66.667V63.3337C47.5 61.953 48.6193 60.8337 50 60.8337C51.3807 60.8337 52.5 61.953 52.5 63.3337V66.667C52.5 68.0477 51.3807 69.167 50 69.167Z" fill="#FF5071" fill-opacity="0.3" />
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M40 75.8335C38.6193 75.8335 37.5 74.7142 37.5 73.3335V66.6668C37.5 65.2861 38.6193 64.1668 40 64.1668C41.3807 64.1668 42.5 65.2861 42.5 66.6668V73.3335C42.5 74.7142 41.3807 75.8335 40 75.8335Z" fill="#FF5071" fill-opacity="0.3" />
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M42.5498 39.8638V49.1069H37.5498V39.8638C37.5498 38.4832 38.6691 37.3638 40.0498 37.3638C41.4305 37.3638 42.5498 38.4832 42.5498 39.8638Z" fill="#FF5071" fill-opacity="0.3" />
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M15.4538 51.917C12.5234 48.7188 11.3916 43.8996 13.8259 39.3619L29.3867 10.3543C33.8162 2.09727 46.2732 2.10561 50.6895 10.3696L66.1832 39.3619C68.6095 43.9026 67.4708 48.7191 64.5365 51.9129C61.6185 55.0891 56.8722 56.7529 51.9272 55.2723L40.2872 51.7874C40.1318 51.7408 39.9658 51.7407 39.8102 51.7871L28.0612 55.2914C23.1134 56.7671 18.368 55.0975 15.4538 51.917ZM19.1403 48.5392C20.8301 50.3834 23.6159 51.3996 26.6321 50.5L38.3812 46.9957C39.4708 46.6706 40.6318 46.6712 41.7215 46.9974L53.3612 50.4824C56.3755 51.3849 59.1622 50.3723 60.8545 48.5302C62.5308 46.7058 63.0792 44.1623 61.7732 41.7186L46.2798 12.7263C43.7458 7.9846 36.3352 7.97827 33.7928 12.7179L18.2319 41.7256C16.9216 44.1683 17.4667 46.7126 19.1403 48.5392Z" fill="#FF5071" />
                        </svg>
                    </div>
                    <h1 className='text-primary text-center text-xl font-medium'>Kudos!</h1>
                    <div className="md:max-w-[468px] mx-auto mt-7">
                        <p className='text-center text-primary text-sm'>A specialist will contact you shortly. No more actions are required for now. In the meantime, catch up on our latest blog posts.</p>
                        <div className="flex items-center justify-center my-8 space-x-5">
                            <Link href="/maintainance" className='bg-white border border-stroke py-4 px-6 rounded-lg text-secondaryText text-base cursor-pointer'>Close</Link>
                            <Link href="/" className='bg-brand py-4 px-6 rounded-lg text-white text-base cursor-pointer'>Visit our blog</Link>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}

export default kudos