import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Link from 'next/link'
import Footer from '@/components/Footer'
import Sidebar from '@/components/Sidebar';
import HondaLogo from '../assets/Honda.png'
import Image from 'next/image';

const maintainance = () => {
  return (
    <>
      <Head>
        <title>LegitCar | Maintainance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-between">
        <Sidebar />
        <div className="flex-1 min-h-screen bg-grayBg">
          <Navbar page={"Maintainance"} />
          <div className="p-5">
            <div className="flex items-center justify-center md:justify-end mt-4 mb-8 space-x-5">
              <Link href="/addVehicle" className='bg-white border border-stroke py-4 px-6 rounded-lg text-secondaryText text-base cursor-pointer'>Add a vehicle</Link>
              <Link href="/services" className='bg-brand py-4 px-6 rounded-lg text-white text-base cursor-pointer'>Book Service</Link>
            </div>
            <div className="max-w-5xl md:mx-auto bg-white border border-dashboardBorders rounded-lg opacity-[90%] mb-20">

              <table className='w-full hidden md:table pb-14'>
                <thead>
                  <tr className="bg-grayBg">
                    <th className="px-6 py-3 text-start text-grayTable text-xs font-medium">VIN / Chasis number</th>
                    <th className="px-6 py-3 text-start text-grayTable text-xs font-medium">Model</th>
                    <th className="px-6 py-3 text-start text-grayTable text-xs font-medium">Date created</th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-dashboardBorders">
                  <tr>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      5TDZK23C78S210350
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      TOYOTA Camry 2009
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      Fri 30th May, 2022 05:31PM
                    </td>
                  </tr>
                  <tr>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      5TDZK23C78S210350
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      TOYOTA Camry 2009
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      Fri 30th May, 2022 05:31PM
                    </td>
                  </tr>
                  <tr>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      5TDZK23C78S210350
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      TOYOTA Camry 2009
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      Fri 30th May, 2022 05:31PM
                    </td>
                  </tr>
                  <tr>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      5TDZK23C78S210350
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      TOYOTA Camry 2009
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      Fri 30th May, 2022 05:31PM
                    </td>
                  </tr>
                  <tr>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      5TDZK23C78S210350
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      TOYOTA Camry 2009
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      Fri 30th May, 2022 05:31PM
                    </td>
                  </tr>
                  <tr>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      5TDZK23C78S210350
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      TOYOTA Camry 2009
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      Fri 30th May, 2022 05:31PM
                    </td>
                  </tr>
                  <tr>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      5TDZK23C78S210350
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      TOYOTA Camry 2009
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      Fri 30th May, 2022 05:31PM
                    </td>
                  </tr>
                  <tr>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      5TDZK23C78S210350
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      TOYOTA Camry 2009
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      Fri 30th May, 2022 05:31PM
                    </td>
                  </tr>
                  <tr>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      5TDZK23C78S210350
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      TOYOTA Camry 2009
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      Fri 30th May, 2022 05:31PM
                    </td>
                  </tr>
                  <tr>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      5TDZK23C78S210350
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      TOYOTA Camry 2009
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      Fri 30th May, 2022 05:31PM
                    </td>
                  </tr>
                  <tr>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      5TDZK23C78S210350
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      TOYOTA Camry 2009
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      Fri 30th May, 2022 05:31PM
                    </td>
                  </tr>
                  <tr>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      5TDZK23C78S210350
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      TOYOTA Camry 2009
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      Fri 30th May, 2022 05:31PM
                    </td>
                  </tr>
                  <tr>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      5TDZK23C78S210350
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      TOYOTA Camry 2009
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      Fri 30th May, 2022 05:31PM
                    </td>
                  </tr>
                  <tr>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      5TDZK23C78S210350
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      TOYOTA Camry 2009
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-primary text-sm">
                      Fri 30th May, 2022 05:31PM
                    </td>
                  </tr>
                </tbody>
              </table>

              <div className="bg-white border border-stroke rounded-lg m-5 p-10 shadow-main md:hidden">
                <div className="mb-5 flex items-center space-x-8">
                  <Image src={HondaLogo} alt="Car logo" className='w-20 h-20 p-4 bg-grayBg rounded-full' />
                  <div className="">
                    <p className='text-primary font-semibold'>Honda</p>
                    <p className='text-secondaryText font-medium text-sm'>JHLRE4859C401526Z</p>
                  </div>
                </div>
                <div className="mb-8">
                  <h5 className='text-grayTable text-xs mb-2'>Start date</h5>
                  <p className='text-primary text-sm'>N / A</p>
                </div>
                <div className="mb-8">
                  <h5 className='text-grayTable text-xs mb-2'>Completed date</h5>
                  <p className='text-primary text-sm'>N / A</p>
                </div>
                <div className="mb-8">
                  <h5 className='text-grayTable text-xs mb-2'>Plan</h5>
                  <p className='text-primary text-sm'>6-months Plan</p>
                </div>
                <div className="mb-8">
                  <h5 className='text-grayTable text-xs mb-2'>Status</h5>
                  <button className='text-sm text-secondaryText bg-grayBg px-3 py-1 rounded-2xl'>No maintenance</button>
                </div>
              </div>
              
              <div className="bg-white border border-stroke rounded-lg m-5 p-10 shadow-main md:hidden">
                <div className="mb-5 flex items-center space-x-8">
                  <Image src={HondaLogo} alt="Car logo" className='w-20 h-20 p-4 bg-grayBg rounded-full' />
                  <div className="">
                    <p className='text-primary font-semibold'>Honda</p>
                    <p className='text-secondaryText font-medium text-sm'>JHLRE4859C401526Z</p>
                  </div>
                </div>
                <div className="mb-8">
                  <h5 className='text-grayTable text-xs mb-2'>Start date</h5>
                  <p className='text-primary text-sm'>N / A</p>
                </div>
                <div className="mb-8">
                  <h5 className='text-grayTable text-xs mb-2'>Completed date</h5>
                  <p className='text-primary text-sm'>N / A</p>
                </div>
                <div className="mb-8">
                  <h5 className='text-grayTable text-xs mb-2'>Plan</h5>
                  <p className='text-primary text-sm'>6-months Plan</p>
                </div>
                <div className="mb-8">
                  <h5 className='text-grayTable text-xs mb-2'>Status</h5>
                  <button className='text-sm text-orangeText bg-orangeOverlay px-3 py-1 rounded-2xl'>No maintenance</button>
                </div>
              </div>

              <div className="bg-white border border-stroke rounded-lg m-5 p-10 shadow-main md:hidden">
                <div className="mb-5 flex items-center space-x-8">
                  <Image src={HondaLogo} alt="Car logo" className='w-20 h-20 p-4 bg-grayBg rounded-full' />
                  <div className="">
                    <p className='text-primary font-semibold'>Honda</p>
                    <p className='text-secondaryText font-medium text-sm'>JHLRE4859C401526Z</p>
                  </div>
                </div>
                <div className="mb-8">
                  <h5 className='text-grayTable text-xs mb-2'>Start date</h5>
                  <p className='text-primary text-sm'>N / A</p>
                </div>
                <div className="mb-8">
                  <h5 className='text-grayTable text-xs mb-2'>Completed date</h5>
                  <p className='text-primary text-sm'>N / A</p>
                </div>
                <div className="mb-8">
                  <h5 className='text-grayTable text-xs mb-2'>Plan</h5>
                  <p className='text-primary text-sm'>6-months Plan</p>
                </div>
                <div className="mb-8">
                  <h5 className='text-grayTable text-xs mb-2'>Status</h5>
                  <button className='text-sm text-blue bg-blueOverlay px-3 py-1 rounded-2xl'>No maintenance</button>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  )
}

export default maintainance