import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Link from 'next/link'
import { useState } from 'react'

const services = () => {
    
    const services = [
        { id: 1, name: 'Oil change' },
        { id: 2, name: 'Car wash' },
        { id: 3, name: 'Tyre puncture & alignment' },
        { id: 4, name: 'Battery replacement' },
        { id: 5, name: 'Cooling fan repair' },
        { id: 6, name: 'Other' }
    ]

    const [selectedServices, setSelectedServices] = useState([])

    function handleServiceClick(serviceId) {
        const isSelected = selectedServices.includes(serviceId)
        if (isSelected) {
            setSelectedServices(selectedServices.filter(id => id !== serviceId))
        } else {
            setSelectedServices([...selectedServices, serviceId])
        }
    }

    return (
        <>
            <Head>
                <title>LegitCar | Services</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="min-h-screen bg-grayBg">
                <Navbar page={"Maintainance"} />
                <div className="px-5">
                    <div className="flex items-center justify-end mt-4 mb-8">
                        <Link href="/maintainance" className='cursor-pointer'>
                            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <rect width="24" height="24" rx="12" fill="#475467" />
                                <g clip-path="url(#clip0_3616_84485)">
                                    <path d="M8.41369 15.9999C8.30841 15.9999 8.20304 15.96 8.12298 15.8793C7.96226 15.7186 7.96226 15.4579 8.12298 15.2972L15.2991 8.1211C15.4599 7.96028 15.7204 7.96028 15.8812 8.1211C16.0419 8.28182 16.0419 8.54239 15.8812 8.70311L8.70499 15.8793C8.62433 15.96 8.51906 15.9999 8.41369 15.9999Z" fill="white" />
                                    <path d="M15.5904 16C15.4851 16 15.3797 15.96 15.2997 15.8793L8.12298 8.70265C7.96226 8.54183 7.96226 8.28126 8.12298 8.12054C8.2837 7.95982 8.54427 7.95982 8.70499 8.12054L15.8812 15.2972C16.0419 15.4579 16.0419 15.7186 15.8812 15.8793C15.8005 15.96 15.6952 16 15.5904 16Z" fill="white" />
                                </g>
                                <defs>
                                    <clipPath id="clip0_3616_84485">
                                        <rect width="8" height="8" fill="white" transform="translate(8 8)" />
                                    </clipPath>
                                </defs>
                            </svg>
                        </Link>
                    </div>

                    <div className="flex flex-col items-center justify-center space-y-10">
                        <h2 className='text-primary text-xl font-medium'>What service(s) do you want to book?</h2>
                        <p className='text-primary text-sm font-normal text-center px-14'>Choose the maintenance service(s) you want from below. Select as many as your vehicle requires.</p>
                    </div>
                    <div className="py-14 md:max-w-[468px] mx-auto">
                        <div className="flex flex-wrap gap-4 mb-8 mx-8">
                            {services.map(service => (
                                <div
                                    key={service.id}
                                    className={`py-2 px-4 rounded-lg border font-normal ${selectedServices.includes(service.id) ? 'bg-overlay text-brand border-brand' : 'bg-white text-primary border-stroke'
                                        }`}
                                    onClick={() => handleServiceClick(service.id)}
                                >
                                    <div className="flex items-center space-x-2">
                                        {selectedServices.includes(service.id) && (
                                            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                <path fill-rule="evenodd" clip-rule="evenodd" d="M13.7422 3.76606C14.0221 4.01101 14.0475 4.43773 13.7985 4.71409L6.78928 12.4939C6.53898 12.7717 6.10923 12.7894 5.83699 12.5331L1.78097 8.71475C1.52802 8.47661 1.50381 8.07981 1.72083 7.80855C1.96029 7.50921 2.40623 7.46801 2.69123 7.72435L5.83815 10.5549C6.11163 10.8009 6.53268 10.7789 6.77907 10.5058L12.8081 3.82121C13.052 3.5507 13.4681 3.52618 13.7422 3.76606Z" fill="#8E44AD" />
                                            </svg>

                                        )}
                                        <p>{service.name}</p>
                                    </div>
                                </div>
                            ))}
                        </div>
                        <div className="flex items-center justify-center mt-10">
                            <Link className='bg-[#8E44AD] px-14 py-3 rounded-lg w-auto text-white font-medium' href="/kudos">Submit</Link>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}

export default services